baseURL = 'https://java.crazyfrank.top/'
languageCode = 'zh-cn'
title = 'Java 后端开发教程'
contentDir = "content"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableGitInfo = true

# Docsy theme configuration
[module]
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

[params]
  logo = "/logo.png"

  # User interface configuration
  [params.ui]
    sidebar_menu_compact = false
    breadcrumb_disable = false
    sidebar_search_disable = false
    navbar_logo = true
    footer_about_enable = true
    navbar_translucent_over_cover_disable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

[menu]
  [[menu.main]]
    name = "课程首页"
    url = "/"
    weight = 10
